- platform: Mastodon
  username: "@theverygaming@wetdry.world"
  url: https://wetdry.world/@theverygaming
  boxicons-logo: bxl-mastodon
- platform: Discord
  username: "@e820"
  url: https://discord.com/users/336043438921351171
  boxicons-logo: bxl-discord-alt
- platform: GitHub
  username: "theverygaming"
  url: https://github.com/theverygaming
  boxicons-logo: bxl-github
- platform: YouTube
  url: https://www.youtube.com/channel/UC3pWNtgvZVzsZHQJ2jGlhVA
  boxicons-logo: bxl-youtube
- platform: AniList
  url: https://anilist.co/user/theverygaming/animelist
- platform: Twitter
  username: "@theverygaming"
  url: https://twitter.com/theverygaming
  boxicons-logo: bxl-twitter
