name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync python3 python3-pip tidy
          pip install Mako

      - name: generate
        run: |
          ./generate.sh

      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{runner.workspace}}/website/out
